Quiz answers
1. E
2. A

In [2]:
import numpy as np

In [4]:
x = np.arange(4)
y = np.arange(100, 104)
print(x)
print(y)

[0 1 2 3]
[100 101 102 103]


In [5]:
np.concatenate([x,y]) # Notice how the arg is a list

array([  0,   1,   2,   3, 100, 101, 102, 103])

In [6]:
np.concatenate([x,y], axis = 0) # same thing

array([  0,   1,   2,   3, 100, 101, 102, 103])

In [9]:
np.concatenate([x,y], axis = 1) # error because x and y are 1D.
# try converting them into 2D arrays of just one row.
# axis specifies row or column. column = 0, row = 1.

AxisError: axis 1 is out of bounds for array of dimension 1

In [10]:
x.shape

(4,)

In [13]:
x.reshape(1,4)

array([[0, 1, 2, 3]])

In [14]:
y.reshape(1,4)

array([[100, 101, 102, 103]])

In [15]:
np.concatenate([x.reshape(1,4), y.reshape(1,4)], axis = 0)

array([[  0,   1,   2,   3],
       [100, 101, 102, 103]])

In [11]:
np.vstack([x,y]) # or do vertical stack

array([[  0,   1,   2,   3],
       [100, 101, 102, 103]])

In [16]:
xm = np.arange(6).reshape([2,3])
ym = np.arange(100,106,1).reshape([2,3])
print(xm)
print(ym)

[[0 1 2]
 [3 4 5]]
[[100 101 102]
 [103 104 105]]


In [17]:
xm.shape

(2, 3)

In [18]:
ym.shape

(2, 3)

In [19]:
print(np.concatenate([xm,ym])) # default behavior is axis = 0

[[  0   1   2]
 [  3   4   5]
 [100 101 102]
 [103 104 105]]


In [20]:
print(np.concatenate([xm,ym], axis=1))

[[  0   1   2 100 101 102]
 [  3   4   5 103 104 105]]


In [21]:
np.vstack([xm,ym])

array([[  0,   1,   2],
       [  3,   4,   5],
       [100, 101, 102],
       [103, 104, 105]])

In [22]:
np.hstack([xm,ym])

array([[  0,   1,   2, 100, 101, 102],
       [  3,   4,   5, 103, 104, 105]])

In [23]:
print(x)
print(y)

[0 1 2 3]
[100 101 102 103]


In [24]:
# Vectorized (element-wise) math operators

In [25]:
x + 5

array([5, 6, 7, 8])

In [26]:
x + y # elementwise

array([100, 102, 104, 106])

In [28]:
x * y

array([  0, 101, 204, 309])

In [29]:
np.sum(x * y) # dot product

614

In [30]:
print(xm)
print(ym)

[[0 1 2]
 [3 4 5]]
[[100 101 102]
 [103 104 105]]


In [31]:
xm + 5 # broadcasting, ie recycling

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [32]:
np.multiply(xm, ym) # element-wise multiplication

array([[  0, 101, 204],
       [309, 416, 525]])

In [33]:
np.dot(xm, ym.T) # matrix multiplication

array([[ 305,  314],
       [1214, 1250]])

In [34]:
xm @ ym.T # matrix multiplication

array([[ 305,  314],
       [1214, 1250]])

In [36]:
# trig functions are found in math and numpy
theta = np.linspace(0, np.pi, 5) # 0 to pi, divided into 5. these are our angles
theta

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [38]:
np.sin(theta)

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

In [39]:
x = np.array([1, 10, 100])
print(np.log(x)) # ln
print(np.log10(x)) # log base 10

[0.         2.30258509 4.60517019]
[0. 1. 2.]


In [40]:
np.exp(x) # e to the power of x

array([2.71828183e+00, 2.20264658e+04, 2.68811714e+43])

In [41]:
np.exp2(x) # 2 to the power of x

array([2.0000000e+00, 1.0240000e+03, 1.2676506e+30])

In [42]:
np.power(x, 2) # x to the power of 2

array([    1,   100, 10000])

In [43]:
# np.sum() is faster than sum(), but behaves differently sometimes.
# you should just use np.sum() if you already have numpy loaded.
x = np.arange(100)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [44]:
sum(x)

4950

In [45]:
np.sum(x) # same as above

4950

In [47]:
big_array = np.random.rand(10000)
# %timeit returns the amount of time it takes to run the command
%timeit sum(big_array)
%timeit np.sum(big_array) # so much faster!

847 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
6.07 µs ± 215 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [48]:
min(big_array)

7.308258197002981e-05

In [49]:
max(big_array)

0.9999250939231508

In [51]:
np.random.seed(1)
M = np.arange(12) # same as np.random.random((3,4))
np.random.shuffle(M)
M = np.reshape(M, [3,4])
print(M)

[[ 2  3  4 10]
 [ 1  6  0  7]
 [11  9  8  5]]


In [52]:
sum(M) # column-wise

array([14, 18, 12, 22])

In [53]:
np.sum(M) # entire matrix

66

In [54]:
np.sum(M, axis = 0) # sum the columns

array([14, 18, 12, 22])

In [55]:
np.sum(M, axis = 1) # sum the rows

array([19, 14, 33])

In [56]:
np.min(M, axis = 0) # find min of each column

array([1, 3, 0, 5])

In [57]:
# nan is used as a missing value
# nan only exists in float type

x = float("nan") # how to create a nan
x

nan

In [58]:
np.sum([x, 2])

nan

In [59]:
# lots of np functions have nansafe versions
np.nansum([x, 2]) # like na.rm

2.0

In [60]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)

[5 7 9]


In [61]:
c = np.array([7,8])
print(a + b + c) # doesn't work. dimensions don't match

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [62]:
e = np.ones([3,3])
print(e)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [63]:
print(a)

[1 2 3]


In [65]:
a + e # a gets "broadcast" all across the three rows

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [67]:
e = np.arange(10).reshape((10,1))
f = np.arange(10)
print(e)
print(f)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 2 3 4 5 6 7 8 9]


In [68]:
print(e + f) # broadcasting!

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


In [69]:
# numpy boolean operators are diff

x = np.arange(6)
print(x)
print(x < 3) # vectorized results

[0 1 2 3 4 5]
[ True  True  True False False False]


In [70]:
print(x[x < 3]) # subsetting

[0 1 2]


In [71]:
np.sum(x > 3) # sums the subvector

2

In [72]:
~(x > 3) # tilda denotes not, similar to ! in c++

array([ True,  True,  True,  True, False, False])

In [73]:
# same thing with matrices
y = np.arange(12).reshape([3,4])
print(y)
print(y > 3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [74]:
# bit-wise operators &, |, ^
a = np.array([True, True, False, False])
b = np.array([True, False, True, False])
print(a)
print(b)

[ True  True False False]
[ True False  True False]


In [75]:
print(a & b)

[ True False False False]


In [76]:
print(a | b)

[ True  True  True False]


In [77]:
print(a ^ b) # exclusive or

[False  True  True False]


In [78]:
print(~a)

[False False  True  True]


In [79]:
np.any(a)

True

In [80]:
np.all(a)

False

In [82]:
# fancy indexing is allowed in numpy, but not in base
x = np.array(['a', 'b', 'c', 'd', 'e', 'f'])
print(x)
indices = [0, 1, 5]
print(x[indices]) # you can subset an array with a list/2d array of indices

['a' 'b' 'c' 'd' 'e' 'f']
['a' 'b' 'f']


In [84]:
a = np.random.rand(10)
print(a)

[0.39676747 0.53881673 0.41919451 0.6852195  0.20445225 0.87811744
 0.02738759 0.67046751 0.4173048  0.55868983]


In [85]:
np.sort(a)

array([0.02738759, 0.20445225, 0.39676747, 0.4173048 , 0.41919451,
       0.53881673, 0.55868983, 0.67046751, 0.6852195 , 0.87811744])

In [86]:
np.argsort(a) # returns the indices that you would need to sort a

array([6, 4, 0, 8, 2, 1, 9, 7, 3, 5])

In [89]:
print(M)
M[0,:] # selecting a row

[[ 2  3  4 10]
 [ 1  6  0  7]
 [11  9  8  5]]


array([ 2,  3,  4, 10])

In [91]:
M[2,:].argsort() # returns the indices you would need to sort that row

array([3, 2, 1, 0])